services:
  bastion:
    build:
      context: ./container
      dockerfile: Dockerfile
    volumes:
      - ./container:/app
    working_dir: /app
    tty: true
    environment:
      - TZ=Asia/Tokyo
